-- ==========================================
-- MINTEDLORE ENTERPRISE SCHEMA (v2)
-- Run this in your Supabase SQL Editor.
-- ==========================================

-- 1. APP USERS & ROLES
-- We use "app_users" instead of "user" because "user" is a reserved keyword in PostgreSQL
CREATE TABLE public.app_users (
    wallet_address TEXT PRIMARY KEY,
    role TEXT DEFAULT 'user' NOT NULL,
    added_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PUBLIC PROFILES
CREATE TABLE public.public_profile (
    public_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT REFERENCES public.app_users(wallet_address) ON DELETE CASCADE,
    username TEXT,
    profile_image TEXT,
    cover_image TEXT,
    twitter_handle TEXT,
    telegram_handle TEXT,
    public_nfts JSONB DEFAULT '[]'::jsonb
);

-- 3. CORE COLLECTIONS & GAMES
CREATE TABLE public.collection (
    collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT REFERENCES public.app_users(wallet_address),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    collection_address TEXT,
    category TEXT DEFAULT 'nft', -- 'nft' or 'game'
    preferred_view TEXT DEFAULT 'grid',
    vip_threshold INT DEFAULT 0,
    description TEXT,
    image TEXT,
    twitter_url TEXT,
    website_url TEXT,
    theme_settings JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. STORIES (Curated Narrative Hubs)
CREATE TABLE public.stories (
    stories_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT REFERENCES public.collection(collection_id) ON DELETE CASCADE,
    wallet_address TEXT REFERENCES public.app_users(wallet_address),
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    collection_address TEXT,
    preferred_view TEXT DEFAULT 'grid',
    vip_threshold INT DEFAULT 0,
    description TEXT,
    image TEXT,
    theme_settings JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. STORY ASSETS (NFTs placed within a story)
CREATE TABLE public.stories_selection (
    stories_selection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stories_id BIGINT REFERENCES public.stories(stories_id) ON DELETE CASCADE,
    collection_id BIGINT REFERENCES public.collection(collection_id) ON DELETE CASCADE,
    mint_address TEXT NOT NULL,
    added_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ANALYTICS (Daily Views Aggregation)
CREATE TABLE public.analytics_daily_views (
    analytics_daily_views_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stories_id BIGINT REFERENCES public.stories(stories_id) ON DELETE CASCADE,
    collection_id BIGINT REFERENCES public.collection(collection_id) ON DELETE CASCADE,
    view_date DATE NOT NULL DEFAULT CURRENT_DATE,
    view_count INT DEFAULT 1,
    UNIQUE(collection_id, stories_id, view_date)
);

-- 7. PROMOTIONS & ADS (Dynamic Hero Banners)
CREATE TABLE public.promotions (
    promotions_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placement TEXT DEFAULT 'hero', -- 'hero' or 'sidebar'
    badge_text TEXT, -- e.g., "PLATFORM NEWS"
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT NOT NULL,
    button_text TEXT DEFAULT 'Learn More',
    button_url TEXT, -- Primary button link
    button_2_text TEXT, -- Secondary button text (e.g., "Update Hub")
    button_2_url TEXT, -- Secondary button link
    is_active BOOLEAN DEFAULT true,
    display_order INT DEFAULT 0,
    start_date TIMESTAMPTZ, -- Optional: when the ad should start showing
    end_date TIMESTAMPTZ,   -- Optional: when the ad should stop showing
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.public_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stories_selection ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_daily_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promotions ENABLE ROW LEVEL SECURITY;

-- READ: Everyone can see everything (Public Galleries)
CREATE POLICY "Allow public read" ON public.public_profile FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON public.collection FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON public.stories FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON public.stories_selection FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON public.analytics_daily_views FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON public.promotions FOR SELECT USING (true);

-- WRITE (Users/Profiles): Users can edit their own profiles
CREATE POLICY "Allow users to edit own profile" ON public.public_profile 
FOR ALL USING (wallet_address = current_setting('request.jwt.claims', true)::json->>'sub');

-- WRITE (Collections): Only the owner or an admin can edit a collection
CREATE POLICY "Allow owners to manage collections" ON public.collection
FOR ALL USING (
    wallet_address = current_setting('request.jwt.claims', true)::json->>'sub' 
    OR 
    EXISTS (SELECT 1 FROM public.app_users WHERE wallet_address = current_setting('request.jwt.claims', true)::json->>'sub' AND role = 'admin')
);

-- WRITE (Stories): Only the owner or an admin can edit stories
CREATE POLICY "Allow owners to manage stories" ON public.stories
FOR ALL USING (
    wallet_address = current_setting('request.jwt.claims', true)::json->>'sub'
    OR 
    EXISTS (SELECT 1 FROM public.app_users WHERE wallet_address = current_setting('request.jwt.claims', true)::json->>'sub' AND role = 'admin')
);

-- WRITE (Promotions): Only an admin can manage ads/promotions
CREATE POLICY "Allow admins to manage promotions" ON public.promotions
FOR ALL USING (
    EXISTS (SELECT 1 FROM public.app_users WHERE wallet_address = current_setting('request.jwt.claims', true)::json->>'sub' AND role = 'admin')
);

-- TRIGGERS (Auto-update timestamps)
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;   
END;
$$ language 'plpgsql';

CREATE TRIGGER update_collection_modtime
BEFORE UPDATE ON collection
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

CREATE TRIGGER update_stories_modtime
BEFORE UPDATE ON stories
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
