-- Run this inside the Supabase SQL Editor to create your fully configured Database.

-- 1. SUPER ADMINS TABLE: Tracks wallets that have God-mode access
CREATE TABLE super_admins (
  wallet_address TEXT PRIMARY KEY,
  added_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. COMMUNITIES TABLE
CREATE TABLE communities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_wallet TEXT NOT NULL, -- The Solana wallet address of the creator
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  collection_address TEXT NOT NULL,
  preferred_view TEXT NOT NULL DEFAULT 'timeline1',
  vip_threshold INT NOT NULL DEFAULT 1,
  description TEXT,
  image TEXT,
  twitter_url TEXT,
  website_url TEXT,
  theme_settings JSONB DEFAULT '{"primaryColor": "#34d399", "backgroundColor": "#050505", "borderStyle": "rounded-none"}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Turn on Row Level Security (RLS)
ALTER TABLE communities ENABLE ROW LEVEL SECURITY;

-- 1. Anyone can view all communities (for your public gallery pages)
CREATE POLICY "Public communities are viewable by everyone." 
  ON communities FOR SELECT 
  USING (true);

-- NOTE ON RLS FOR WEB3: 
-- Because users log in with Solana Wallets instead of passwords, you will typically
-- use Next.js API Routes to verify the wallet signature (using a library like TweetNaCl).
-- Once the signature is verified, your Next.js server will update the database using 
-- the Supabase Service Role Key. 
-- 
-- Therefore, the RLS policies below are written assuming you generate a custom JWT 
-- for the user containing their wallet address. If you handle security entirely in Next.js,
-- you can bypass these specific RLS rules using the Service Key.

-- 2. Authenticated owners can create new communities
CREATE POLICY "Owners can create communities." 
  ON communities FOR INSERT 
  WITH CHECK (auth.jwt()->>'wallet' = owner_wallet);

-- 3. Authenticated owners (or Super Admins) can update communities
CREATE POLICY "Owners and Admins can update communities." 
  ON communities FOR UPDATE 
  USING (
    auth.jwt()->>'wallet' = owner_wallet 
    OR 
    EXISTS (SELECT 1 FROM super_admins WHERE wallet_address = auth.jwt()->>'wallet')
  );

-- 4. Authenticated owners (or Super Admins) can delete communities
CREATE POLICY "Owners and Admins can delete communities." 
  ON communities FOR DELETE 
  USING (
    auth.jwt()->>'wallet' = owner_wallet 
    OR 
    EXISTS (SELECT 1 FROM super_admins WHERE wallet_address = auth.jwt()->>'wallet')
  );

-- 5. Trigger to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;   
END;
$$ language 'plpgsql';

CREATE TRIGGER update_communities_modtime
BEFORE UPDATE ON communities
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- ─────────────────────────────────────────────────────────────────────────────
-- COMMUNITY TYPES UPGRADE
-- Run these statements to upgrade an existing communities table.
-- ─────────────────────────────────────────────────────────────────────────────

-- Add collection_type column (type_a = full ME collection, type_b = curated sub)
ALTER TABLE communities
  ADD COLUMN IF NOT EXISTS collection_type TEXT NOT NULL DEFAULT 'type_a'
    CHECK (collection_type IN ('type_a', 'type_b'));

-- Add parent reference for type_b communities
ALTER TABLE communities
  ADD COLUMN IF NOT EXISTS parent_community_id BIGINT
    REFERENCES communities(id) ON DELETE CASCADE;

-- Prevent duplicate type_a communities for the same Magic Eden collection
CREATE UNIQUE INDEX IF NOT EXISTS unique_type_a_collection
  ON communities (collection_address)
  WHERE collection_type = 'type_a';

-- ─────────────────────────────────────────────────────────────────────────────
-- COMMUNITY_NFTS TABLE  (stores hand-picked mints for Type B communities)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS community_nfts (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  community_id    BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
  mint_address    TEXT NOT NULL,
  name            TEXT,
  image_url       TEXT,
  added_at        TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  UNIQUE(community_id, mint_address)
);

ALTER TABLE community_nfts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read community NFTs."
  ON community_nfts FOR SELECT USING (true);

CREATE POLICY "Owners can manage their community NFTs."
  ON community_nfts FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM communities c
      WHERE c.id = community_id
        AND c.owner_wallet = auth.jwt()->>'wallet'
    )
  );
